#Queries for all worksets by one user
#Demo user is hardcoded, needs to be linked to the front end authentication system. 
select ?s ?o where {{
  ?s ?p ?o.
  filter(regex(str(?o), "Demo user", "i")) .
}}
